import React from 'react';
import Landing from '../layout/Landing';

const TermsOfService = () => {
  return (
    <Landing header="Terms of Service">
      <div className="container py-4 mt-5">
        {/* <div className="parent1">
          <center> <h1><u> Terms and Conditions For SmartInvoiceX</u></h1></center><br />
          <p> <h3>Welcome to the Invoice Generator service operated by SmartInvoiceX. These Terms and Conditions(Terms) govern your access to and use of the Service. By accessing or using the service, you confirm that you have read, understood and agree to be bound by these Terms. . If you do not agree, please refrain from using the service</h3></p><br />
          <section>
            <h4 className="">1.Description Of the Service</h4>
            <p>
              The Service provides users with a platform to generate invoices by inputting relevant business, client, and transaction details. The Service aims to simplify the process of invoice creation but does not guarantee legal, tax, or regulatory compliance in any jurisdiction
            </p>
          </section>

          <section>
            <h4 className="">2.User Obligations and Responsibilities</h4>
            <p>
              <h5>By using the Service, you agree that</h5>
            </p>
            <ul>
              <li>You are solely responsible for the data you input into the Service, including names, addresses, tax IDs, pricing, terms of sale, and all other information included in any invoice generated.</li>
              <li>You will use the Service in accordance with all applicable local, state, national, and international laws, rules and regulations.</li>
              <li>You will not use the Service to create fraudulent, deceptive or misleading invoices, or to impersonate another person or entity.</li>
              <li>You understand that the Company does not validate, audit, review, or approve the content you generate or submit.</li>




            </ul>
          </section>

          <section>
            <h4 className="">3.Disclaimer of Liability and Legal Exoneration</h4>
            <ul className="list-disc list-inside ml-4">
              <li>The Service is provided “as is”, “as available” and without warranty of any kind, whether express or implied.</li>
              <li>
                The Company makes no representations or warranties of any kind, including but not limited to:</li>
              <ul>
                <li>The accuracy, completeness, or legality of any invoice generated;</li>
                <li>Compliance with tax regulations, accounting standards or business practices;</li>
                <li>oThe enforceability or legal standing of any invoice generated through the Service;</li>
              </ul>
              <li>You acknowledge and agree that the Company is not a legal, tax or financial advisor, and nothing in the service constitutes legal, tax, or accounting advice</li>
              <li>Under no circumstances shall the Company, its affiliates, officers, directors, employees, or agents be held liable for any damages, losses, liabilities, claims, or expenses - whether direct, indirect, incidental, consequential, or punitive – arising from:</li>
              <ul>
                <li>  The use or misuse of the Service</li>
                <li> Any business decisions based on invoices generated by the Service;</li>
                <li>
                  Disputes or legal proceedings between users and Third parties related to the use of the Service;
                </li>
                <li>Any unauthorized access to or use of your data or content</li>




              </ul>


            </ul>
          </section>

          <section>
            <h4 className="">4. Intellectual Property</h4>
            <p>
              All content, branding, and tools provided by this website are the property of the company. Unauthorized use, reproduction, or distribution is prohibited.
            </p>
          </section>

          <section>
            <h4 className="">5. Limitation of Liability</h4>
            <p>
              We are not liable for any damages or losses resulting from the use or inability to use our service. All documents generated are provided "as-is" without warranties of any kind.
            </p>
          </section>

          <section>
            <h4 className="">6. Modifications to Terms</h4>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h4 className="">7. Termination</h4>
            <p>
              We may suspend or terminate your access to the service if you violate these terms or engage in misuse of the platform.
            </p>
          </section>

          <section>
            <h4 className="">8. Contact Us</h4>
            <p>
              For questions about these Terms of Service, please contact us at:<br />
              <strong>Email:</strong> support@yourdomain.com
            </p>
          </section>

          <footer className="pt-6 text-sm text-gray-500 border-t mt-8">
            Effective Date: April 13, 2025
          </footer>
        </div> */}
        <div className="parent1 px-6 md:px-12 py-10 max-w-4xl mx-auto text-gray-800 leading-relaxed">
          <h1 className="text-3xl font-bold text-center mb-8 underline">Terms and Conditions For SmartInvoiceX</h1>

          <p className="mb-6">
            Welcome to the Invoice Generator service operated by SmartInvoiceX (“we”, “us” or “our”). These Terms and Conditions
            (Terms) govern your access to and use of the Service. By accessing or using the service, you confirm that you have
            read, understood and agree to be bound by these Terms. If you do not agree, please refrain from using the service.
          </p>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">1. Description Of the Service</h2>
            <p>
              The Service provides users with a platform to generate invoices by inputting relevant business, client, and
              transaction details. The Service aims to simplify the process of invoice creation but does not guarantee legal,
              tax, or regulatory compliance in any jurisdiction.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">2. User Obligations and Responsibilities</h2>
            <ul className="list-disc list-inside space-y-2">
              <li>You are solely responsible for the data you input into the Service, including names, addresses, tax IDs, pricing, terms of sale, and all other information included in any invoice generated.</li>
              <li>You will use the Service in accordance with all applicable local, state, national, and international laws, rules and regulations.</li>
              <li>You will not use the Service to create fraudulent, deceptive or misleading invoices, or to impersonate another person or entity.</li>
              <li>You understand that the Company does not validate, audit, review, or approve the content you generate or submit.</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">3. Disclaimer of Liability and Legal Exoneration</h2>
            <ul className="list-disc list-inside space-y-2">
              <li>The Service is provided “as is”, “as available” and without warranty of any kind, whether express or implied.</li>
              <li>The Company makes no representations or warranties of any kind, including but not limited to:
                <ul className="list-disc list-inside ml-5 mt-1 space-y-1">
                  <li>The accuracy, completeness, or legality of any invoice generated;</li>
                  <li>Compliance with tax regulations, accounting standards or business practices;</li>
                  <li>The enforceability or legal standing of any invoice generated through the Service;</li>
                </ul>
              </li>
              <li>You acknowledge and agree that the Company is not a legal, tax or financial advisor, and nothing in the service constitutes legal, tax, or accounting advice.</li>
              <li>Under no circumstances shall the Company, its affiliates, officers, directors, employees, or agents be held liable for any damages, losses, liabilities, claims, or expenses – whether direct, indirect, incidental, consequential, or punitive – arising from:
                <ul className="list-disc list-inside ml-5 mt-1 space-y-1">
                  <li>The use or misuse of the Service;</li>
                  <li>Any business decisions based on invoices generated by the Service;</li>
                  <li>Disputes or legal proceedings between users and third parties related to the use of the Service;</li>
                  <li>Any unauthorized access to or use of your data or content.</li>
                </ul>
              </li>
              <li>By using this Service, you expressly waive any and all claims against the Company related to any invoice you generate using the Service.</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">4. User Content and Data Ownership</h2>
            <ul className="list-disc list-inside space-y-2">
              <li>You retain ownership of the content and data you enter into the Service.</li>
              <li>By using the Service, you grant the Company a limited, non-exclusive license to process and store your content for the purpose of providing and improving the Service.</li>
              <li>You are responsible for backing up your data. The Company is not liable for any data loss or corruption.</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">5. Prohibited Uses</h2>
            <p className="mb-2">You agree not to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Generate or distribute false or misleading invoices.</li>
              <li>Violate any applicable laws or regulations.</li>
              <li>Infringe upon the rights of any third party.</li>
              <li>Upload or transmit malicious software or code.</li>
              <li>Interfere with or disrupt the integrity or performance of the Service.</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">6. Intellectual Property Rights</h2>
            <ul className="list-disc list-inside space-y-2">
              <li>All intellectual property related to the Service, including but not limited to software, design, logos, text, and user interface elements, is the exclusive property of the Company.</li>
              <li>You may not copy, modify, distribute, sell, or lease any part of the Service without the Company’s prior written consent.</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">7. Modifications to the Terms</h2>
            <p>
              We reserve the right to change or update these Terms at any time. Changes will become effective immediately upon
              posting. It is your responsibility to review these Terms periodically. Your continued use of the Service after
              changes are posted constitutes your acceptance of the revised Terms.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">8. Termination of Access</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at our sole discretion, without any notice
              or liability, for any reason, including if we believe you have violated these Terms or used the Service
              inappropriately.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">9. Indemnification</h2>
            <p className="mb-2">You agree to indemnify, defend, and hold harmless the Company and its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, obligations, losses, liabilities, costs or debt arising from:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Your use or access to the Service;</li>
              <li>Any content or data you submit through the Service;</li>
              <li>Your violation of these Terms or any applicable law or regulation;</li>
              <li>Your violation of any third-party rights, including intellectual property or privacy rights.</li>
            </ul>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">10. Governing Law and Jurisdiction</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the Federal Government of Nigeria.
              You agree that any legal action or proceeding between you and the Company arising from these Terms or your use of
              the Service shall be brought exclusively in the courts located in Nigeria.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">11. Severability</h2>
            <p>
              If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall remain in
              full force and effect.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">12. Entire Agreement</h2>
            <p>
              These Terms constitute the entire agreement between you and the Company regarding your use of the Service and
              supersede any prior agreements or understandings.
            </p>
          </section>

          <section className="mb-6">
            <h2 className="text-xl font-semibold mb-2">13. Contact Information</h2>
            <p>
              If you have any questions about these Terms, please contact us at: <br />
              <strong>Email:</strong> <a href="mailto:SmartinvoiceX@gmail.com" className="text-blue-600 hover:underline">SmartinvoiceX@gmail.com</a>
            </p>
          </section>

          <footer className="pt-6 text-sm text-gray-500 border-t mt-8 text-center">
            Effective Date: April 13, 2025
          </footer>
        </div>

      </div>
    </Landing>
  );
};

export default TermsOfService;

